### ISSUE TITLE
Docker image crashes every few requests

### ISSUE THREAD

**Issue by Geronimo2015** [Brainicism/bgutil-ytdlp-pot-provider#40]
The docker image version 0.6.1 crashes and restarts every few requests.

Errors like:
```
/app/build/session_manager.js:163

            throw new Error(`Error while attempting to retrieve BG challenge. err = ${e}`);

                  ^

Error: Error while attempting to retrieve BG challenge. err = [object Object]

    at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:48:25

Node.js v20.17.0
```

**Comment by Geronimo2015** [comment]
> The docker image version 0.6.1 crashes and restarts every few requests.
> 
> Errors like:
> 
> ```
> /app/build/session_manager.js:163
> 
>             throw new Error(`Error while attempting to retrieve BG challenge. err = ${e}`);
> 
>                   ^
> 
> Error: Error while attempting to retrieve BG challenge. err = [object Object]
> 
>     at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async /app/build/main.js:48:25
> 
> Node.js v20.17.0
> ```

NOTE:
- the thrown exception makes the container fail and restart
- I'm using a proxy for yt-dlp, maybe that is related

**Comment by Brainicism** [comment]
Hi @Geronimo2015 !
Are you able to reproduce this easily? If so, do you mind using this image: `brainicism/bgutil-ytdlp-pot-provider:d802040e`. I fixed the logging on that line so it should give us a better clue.

**Comment by Geronimo2015** [comment]
> Hi @Geronimo2015 ! Are you able to reproduce this easily? If so, do you mind using this image: `brainicism/bgutil-ytdlp-pot-provider:d802040e`. I fixed the logging on that line so it should give us a better clue.
> 
> EDIT: Can you also specify what type of proxy you're using? HTTPS/SOCKS/etc

Hi,

thanks for looking into this.
I'm using socks5 proxy in this context.


New logging still the same however:
```
Started POT server on port 4416

Received request for visitor data: 'CgsxR05wY09pLXlWayiY5rC7BjIKCgJVUxIEGgAgaw%3D%3D'

Received request for visitor data: 'CgtoMWxqWUVZMTMxNCiY5rC7BjIKCgJVUxIEGgAgPw%3D%3D'

Received request for visitor data: 'CgtjUjBrVVZKaWxyYyiX5rC7BjIKCgJJUhIEGgAgWw%3D%3D'

Received request for visitor data: 'CgtsdHRpb3hkbWpqcyiT5rC7BjIKCgJJUhIEGgAgYw%3D%3D'

/app/build/session_manager.js:163

            throw new Error(`Error while attempting to retrieve BG challenge. err = ${JSON.stringify(e)}`);

                  ^

Error: Error while attempting to retrieve BG challenge. err = {}

    at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:48:25

Node.js v20.18.1
```

**Comment by Brainicism** [comment]
That is strange.. would you happen to have Discord by any chance? If you do, do you mind adding me (user: ohmi) so we can help me repro?

**Comment by Geronimo2015** [comment]
> > Hi @Geronimo2015 ! Are you able to reproduce this easily? If so, do you mind using this image: `brainicism/bgutil-ytdlp-pot-provider:d802040e`. I fixed the logging on that line so it should give us a better clue.
> > EDIT: Can you also specify what type of proxy you're using? HTTPS/SOCKS/etc
> 
> Hi,
> 
> thanks for looking into this. I'm using socks5 proxy in this context.
> 
> New logging still the same however:
> 
> ```
> Started POT server on port 4416
> 
> Received request for visitor data: 'CgsxR05wY09pLXlWayiY5rC7BjIKCgJVUxIEGgAgaw%3D%3D'
> 
> Received request for visitor data: 'CgtoMWxqWUVZMTMxNCiY5rC7BjIKCgJVUxIEGgAgPw%3D%3D'
> 
> Received request for visitor data: 'CgtjUjBrVVZKaWxyYyiX5rC7BjIKCgJJUhIEGgAgWw%3D%3D'
> 
> Received request for visitor data: 'CgtsdHRpb3hkbWpqcyiT5rC7BjIKCgJJUhIEGgAgYw%3D%3D'
> 
> /app/build/session_manager.js:163
> 
>             throw new Error(`Error while attempting to retrieve BG challenge. err = ${JSON.stringify(e)}`);
> 
>                   ^
> 
> Error: Error while attempting to retrieve BG challenge. err = {}
> 
>     at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async /app/build/main.js:48:25
> 
> Node.js v20.18.1
> ```

NOTE: I'm using this in 

> brainicism/bgutil-ytdlp-pot-provider:d802040e

Now I got:

```
/app/build/session_manager.js:184

            throw new Error(`Error while trying to generate PO token. e = ${e}`);

                  ^

Error: Error while trying to generate PO token. e = TypeError: integrityTokenJson is not iterable

    at SessionManager.generatePoToken (/app/build/session_manager.js:184:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:48:25

Node.js v20.18.1
```

**Comment by Brainicism** [comment]
Can you try ` brainicism/bgutil-ytdlp-pot-provider:b09e27401`?

**Comment by Geronimo2015** [comment]
It seems to happen after I get a 403 Forbidden once.
Next request fails.

```
root@39e984414848:/app# yt-dlp --no-continue --extractor-args "youtube:getpot_bgutil_baseurl=http://tasks.bgutil-provider:4416" --proxy socks5://tasks.proxy:9050 https://www.youtube.com/watch?v=lP68wzMZUoA
[youtube+GetPOT] Extracting URL: https://www.youtube.com/watch?v=lP68wzMZUoA
[youtube+GetPOT] lP68wzMZUoA: Downloading webpage
[youtube+GetPOT] lP68wzMZUoA: Downloading ios player API JSON
[GetPOT] BgUtilHTTPPot: Generating POT via HTTP server
[youtube+GetPOT] lP68wzMZUoA: Downloading mweb player API JSON
[youtube+GetPOT] lP68wzMZUoA: Downloading m3u8 information
[info] lP68wzMZUoA: Downloading 1 format(s): 248+251
ERROR: unable to download video data: HTTP Error 403: Forbidden
root@39e984414848:/app# yt-dlp --no-continue --extractor-args "youtube:getpot_bgutil_baseurl=http://tasks.digital_collectors_deps_bgutil-provider:4416" --proxy socks5://tasks.digital_tordeps_torproxy-USA:9050 https://www.youtube.com/watch?v=lP68wzMZUoA
[youtube+GetPOT] Extracting URL: https://www.youtube.com/watch?v=lP68wzMZUoA
[youtube+GetPOT] lP68wzMZUoA: Downloading webpage
[youtube+GetPOT] lP68wzMZUoA: Downloading ios player API JSON
[GetPOT] BgUtilHTTPPot: Generating POT via HTTP server
WARNING: [GetPOT] Failed to fetch PO Token for mweb client: Error reaching POST /get_pot (caused by Remote end closed connection without response)
[youtube+GetPOT] lP68wzMZUoA: Downloading mweb player API JSON
[youtube+GetPOT] lP68wzMZUoA: Downloading m3u8 information
[info] lP68wzMZUoA: Downloading 1 format(s): 248+251
```

than in container of bgutil:
```
    
Started POT server on port 4416
Received request for visitor data: 'CgtUd2xDV3pkcDVIayir8LC7BjIKCgJVUxIEGgAgYA%3D%3D'
Received request for visitor data: 'CgtfR0llNUotT1l4Zyjq8LC7BjIKCgJVUxIEGgAgYw%3D%3D'
Received request for visitor data: 'CgtGT3U0RE9pNE10Zyj98LC7BjIKCgJJUhIEGgAgTQ%3D%3D'
Received request for visitor data: 'CgtsMEpUVlZMNWVGOCiU8bC7BjIKCgJJUhIEGgAgLg%3D%3D'
Received request for visitor data: 'CgtiOWFObUJ6akthZyis8bC7BjIKCgJJUhIEGgAgOA%3D%3D'
Received request for visitor data: 'Cgt6bW5JVkdaSDBYOCi-8bC7BjIKCgJJUhIEGgAgJg%3D%3D'
Received request for visitor data: 'CgtoQ1lIaWhDQ0FjUSjX8bC7BjIKCgJVUxIEGgAgWg%3D%3D'
Received request for visitor data: 'Cgtib1JhSzc5YW93VSjs8bC7BjIKCgJVUxIEGgAgXw%3D%3D'

/app/build/session_manager.js:163

            throw new Error(`Error while attempting to retrieve BG challenge. err = ${JSON.stringify(e)}`);

                  ^

Error: Error while attempting to retrieve BG challenge. err = {}

    at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:48:25

Node.js v20.18.1
```

**Comment by Geronimo2015** [comment]
> brainicism/bgutil-ytdlp-pot-provider:b09e27401

```
Started POT server on port 4416

Received request for visitor data: 'CgtzdHhLbTJuS0JiUSiy-bC7BjIKCgJJUhIEGgAgOQ%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: undefined"}. err.stack = Error: Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: undefined"}

    at SessionManager.generatePoToken (/app/build/session_manager.js:163:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29
```

**Comment by shirt-dev** [comment]
YouTube appears to be blocking axios requests. I tried using https://www.npmjs.com/package/got instead and had no issues retrieving the BG challenge.

**Comment by Brainicism** [comment]
> YouTube appears to be blocking axios requests. I tried using https://www.npmjs.com/package/got instead and had no issues retrieving the BG challenge.

Good find! This is probably because of Axios' default user-agent. Fixing in #42

**Comment by grqz** [comment]
@Geronimo2015 I was unable to reproduce the issue. Can you try the latest release(0.7.0)?

**Comment by jeroenvanderschoot** [comment]
> @Geronimo2015 I was unable to reproduce the issue. Can you try the latest release(0.7.0)?

This works better:
- the container does not crash anymore after 403
- 403's seems to be returned less often
- retrying after failures with different IP works

```
Started POT server on port 4416

Received request for visitor data: 'CgtGLUg0TzBqcFRmWSjMprS7BjIKCgJJUhIEGgAgGw%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while trying to generate PO token. err.name = undefined. err.message = [GenerateIT]: Failed to generate integrity token. err.stack = undefined. err.stack = Error: Error while trying to generate PO token. err.name = undefined. err.message = [GenerateIT]: Failed to generate integrity token. err.stack = undefined

    at SessionManager.generatePoToken (/app/build/session_manager.js:187:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'CgtyOS1OcUxKeF9LbyjTp7S7BjIKCgJJUhIEGgAgYw%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}. err.stack = Error: Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}

    at SessionManager.generatePoToken (/app/build/session_manager.js:166:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'Cgs4Y0g1NTNHNlBvMCjup7S7BjIKCgJJUhIEGgAgVg%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}. err.stack = Error: Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}

    at SessionManager.generatePoToken (/app/build/session_manager.js:166:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'CgstN0JUSVRHTVB1SSiGqLS7BjIKCgJVUxIEGgAgaA%3D%3D'

Received request for visitor data: 'CgtkaC1XeVJvSmw1RSieqLS7BjIKCgJJUhIEGgAgWw%3D%3D'
```

**Comment by Geronimo2015** [comment]
> @Geronimo2015 I was unable to reproduce the issue. Can you try the latest release(0.7.0)?

Started POT server on port 4416

Received request for visitor data: 'CgtGLUg0TzBqcFRmWSjMprS7BjIKCgJJUhIEGgAgGw%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while trying to generate PO token. err.name = undefined. err.message = [GenerateIT]: Failed to generate integrity token. err.stack = undefined. err.stack = Error: Error while trying to generate PO token. err.name = undefined. err.message = [GenerateIT]: Failed to generate integrity token. err.stack = undefined

    at SessionManager.generatePoToken (/app/build/session_manager.js:187:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'CgtyOS1OcUxKeF9LbyjTp7S7BjIKCgJJUhIEGgAgYw%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}. err.stack = Error: Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}

    at SessionManager.generatePoToken (/app/build/session_manager.js:166:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'Cgs4Y0g1NTNHNlBvMCjup7S7BjIKCgJJUhIEGgAgVg%3D%3D'

Failed while generating POT. err.name = Error. err.message = Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}. err.stack = Error: Error while attempting to retrieve BG challenge. err = {"code":2,"message":"[Challenge]: Failed to fetch challenge: 403"}

    at SessionManager.generatePoToken (/app/build/session_manager.js:166:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /app/build/main.js:49:29

Received request for visitor data: 'CgstN0JUSVRHTVB1SSiGqLS7BjIKCgJVUxIEGgAgaA%3D%3D'

Received request for visitor data: 'CgtkaC1XeVJvSmw1RSieqLS7BjIKCgJJUhIEGgAgWw%3D%3D'

**Comment by Geronimo2015** [comment]
> @Geronimo2015 I was unable to reproduce the issue. Can you try the latest release(0.7.0)?

This works better:
- container does not crash anymore after 403
- seem to be getting less 403's
- retrying with different IP after failure works now
