### ISSUE TITLE
Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Server did not respond with a po_token')

### ISSUE THREAD

**Issue by brian6932** [Brainicism/bgutil-ytdlp-pot-provider#94]
The server's responding.
```
❯ node build/main.js
Started POT server on port 4416
Generating POT for redacted||
POT for redacted|| stale or not yet generated, generating...
poToken: redacted
Generating POT for redacted||
POT for redacted|| still fresh, returning cached token
Generating POT for redacted||
POT for redacted|| still fresh, returning cached token
Generating POT for redacted||
POT for redacted|| still fresh, returning cached token
Generating POT for redacted||
POT for redacted|| still fresh, returning cached token
Generating POT for redacted||
POT for redacted|| still fresh, returning cached token
```
```
❯ git rev-parse head
```
301e0c93b222c03c54725a5eb2491259710db453
```
❯ yt-dlp --version
2025.05.30.232602

❯ yt-dlp --quiet -s -F (gcb -Raw)
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
WARNING: [youtube+GetPOT] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Server did not respond with a po_token'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  .
WARNING: [GetPOT] Failed to fetch gvs PO Token for web client: No request handlers configured
WARNING: [GetPOT] Failed to fetch player PO Token for web_safari client: No request handlers configured
WARNING: [youtube+GetPOT] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Server did not respond with a po_token'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  .
WARNING: [GetPOT] Failed to fetch gvs PO Token for web_safari client: No request handlers configured
WARNING: [GetPOT] Failed to fetch player PO Token for web_embedded client: No request handlers configured
WARNING: [GetPOT] Failed to fetch gvs PO Token for web_embedded client: No request handlers configured
WARNING: [youtube+GetPOT] Ye03RRDLsLM: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube+GetPOT] Ye03RRDLsLM: Some web_safari client https formats have been skipped as they are missing a url. YouTube may have enabled the SABR-only or Server-Side Ad Placement experiment for your account. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [GetPOT] Failed to fetch subs PO Token for web client: No request handlers configured
```

I tried both:
```ini
--extractor-args "youtube:formats=dashy;player-client=default,-tv,web_safari,web_embedded;youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js"
```
and:
```ini
--extractor-arg "youtube:formats=dashy;player-client=default,-tv,web_safari,web_embedded"
--extractor-arg youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js
```

**Comment by brian6932** [comment]
> Are both your server and your plugin on 1.0.0?

Yes. This has only started happening on 1.0.0.

> Could you also provide verbose logs with this modified plugin version? This will help narrow down the issue for us as well

<details>
<summary>Sure, it looks like the path's not being parsed.</summary>

```
❯ yt-dlp --rm-cache-dir; yt-dlp -vsF https://www.youtube.com/watch?v=dQw4w9WgXcQ
Removing cache dir ~/.cache\yt-dlp ..
[debug] Command-line config: ['-vsF', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Portable config "~\scoop\apps\yt-dlp-master\current\yt-dlp.conf": ['--extractor-args', 'youtube:formats=dashy;player-client=default,-tv,web_safari,web_embedded;youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2025.05.30.232602 from yt-dlp/yt-dlp-master-builds [3fe72e9ee] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-119779-g6c291232cf-20250531 (setts), ffprobe N-119779-g6c291232cf-20250531
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ~\scoop\apps\yt-dlp-master\current\yt-dlp-plugins\bgutil-ytdlp-pot-provider\yt_dlp_plugins
[debug] Loaded 1860 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot:bgutil:script] Script path doesn't exist: ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external, unavailable)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[debug] [youtube] [pot:bgutil:http] No base_url provided, defaulting to http://127.0.0.1:4416
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
WARNING: [youtube] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Server did not respond with a poToken. Received response: {"po_token": "redacted"}'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  .
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web_safari client via bgutil HTTP server
WARNING: [youtube] [pot] Error fetching PO Token from "bgutil:http" provider: PoTokenProviderError('Server did not respond with a poToken. Received response: {"po_token": "redacted"}'); please report this issue to the provider developer at  https://github.com/Brainicism/bgutil-ytdlp-pot-provider/issues  .
[youtube] dQw4w9WgXcQ: Downloading web safari player API JSON
[youtube] dQw4w9WgXcQ: Downloading web embedded client config
[youtube] dQw4w9WgXcQ: Downloading player 91e7c654-main
[debug] Saving youtube-sts.91e7c654-main to cache
[youtube] dQw4w9WgXcQ: Downloading web embedded player API JSON
[debug] [youtube] dQw4w9WgXcQ: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function 91e7c654-main-109
[debug] Saving youtube-sigfuncs.91e7c654-main-109 to cache
[debug] [youtube] Decrypted nsig Rb1QqMiFTPsSRkeQWd => P_8M3Myus3E5QQ
[debug] Saving youtube-nsig.91e7c654-main to cache
[debug] [youtube] Decrypted nsig mctx25wif7Wcj8PVRs => xPZEvszWBjlDqA
[debug] [youtube] dQw4w9WgXcQ: web client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=web.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function 91e7c654-main-105
[debug] Saving youtube-sigfuncs.91e7c654-main-105 to cache
[debug] [youtube] Decrypted nsig 9Lo5KiLkyOeKsPp65I => fBbo513QY2txkw
WARNING: [youtube] dQw4w9WgXcQ: web_safari client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=web_safari.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for dQw4w9WgXcQ:
ID  EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0 │                  mhtml │ images                         storyboard
sb2 mhtml 80x45        1 │                  mhtml │ images                         storyboard
sb1 mhtml 160x90       1 │                  mhtml │ images                         storyboard
sb0 mhtml 320x180      1 │                  mhtml │ images                         storyboard
233 mp4   audio only     │                  m3u8  │ audio only          unknown    Default, low, IOS
234 mp4   audio only     │                  m3u8  │ audio only          unknown    Default, high, IOS
602 mp4   256x144     13 │ ~  2.04MiB   81k m3u8  │ vp09.00.10.08   81k video only IOS
269 mp4   256x144     25 │ ~  3.95MiB  156k m3u8  │ avc1.4D400C    156k video only IOS
91  mp4   256x144     25 │ ~  3.95MiB  156k m3u8  │ avc1.4D400C         mp4a.40.5  WEB-S
603 mp4   256x144     25 │ ~  3.88MiB  154k m3u8  │ vp09.00.11.08  154k video only IOS
229 mp4   426x240     25 │ ~  5.73MiB  227k m3u8  │ avc1.4D4015    227k video only IOS
92  mp4   426x240     25 │ ~  5.73MiB  227k m3u8  │ avc1.4D4015         mp4a.40.5  WEB-S
604 mp4   426x240     25 │ ~  7.26MiB  287k m3u8  │ vp09.00.20.08  287k video only IOS
230 mp4   640x360     25 │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E    478k video only IOS
93  mp4   640x360     25 │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E         mp4a.40.2  WEB-S
605 mp4   640x360     25 │ ~ 14.26MiB  564k m3u8  │ vp09.00.21.08  564k video only IOS
231 mp4   854x480     25 │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E    660k video only IOS
94  mp4   854x480     25 │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E         mp4a.40.2  WEB-S
606 mp4   854x480     25 │ ~ 19.74MiB  781k m3u8  │ vp09.00.30.08  781k video only IOS
232 mp4   1280x720    25 │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F   1131k video only IOS
95  mp4   1280x720    25 │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F         mp4a.40.2  WEB-S
609 mp4   1280x720    25 │ ~ 29.81MiB 1180k m3u8  │ vp09.00.31.08 1180k video only IOS
270 mp4   1920x1080   25 │ ~123.87MiB 4902k m3u8  │ avc1.640028   4902k video only IOS
96  mp4   1920x1080   25 │ ~123.87MiB 4902k m3u8  │ avc1.640028         mp4a.40.2  WEB-S
614 mp4   1920x1080   25 │ ~ 71.55MiB 2831k m3u8  │ vp09.00.40.08 2831k video only IOS
616 mp4   1920x1080   25 │ ~144.16MiB 5704k m3u8  │ vp09.00.40.08 5704k video only Premium, IOS
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dQw4w9WgXcQ: Downloading 1 format(s): 616+234
```
</details>

**Comment by Brainicism** [comment]
Can you confirm that you re-transpiled the source code for the server (`npx tsc`)? The logs indicate that the server is returning an object only containing `{po_token: string}`, and that was changed in 0.8.3 (to include two other fields), then changed again in 1.0.0 (changed variable casing).

**Comment by pieska** [comment]
same here, I use the script method, 0.8.5 works, 1.0 returns "WARNING: [GetPOT] Failed to fetch gvs PO Token for web client: No request handlers configured", source code has been transpiled.

**Comment by pieska** [comment]
I removed yt-dlp-get-pot plugin because yt-dlp is on 205-05-22 

```
[debug] User config "/home/user/.config/yt-dlp/config": ['-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '-4', '-cio', '%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.3 (CPython x86_64 64bit) - Linux-6.14.8-300.fc42.x86_64-x86_64-with-glibc2.41 (OpenSSL 3.2.4 11 Feb 2025, glibc 2.41)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.47.2, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=lA1BcL2rVNY
[youtube] lA1BcL2rVNY: Downloading webpage
[youtube] lA1BcL2rVNY: Downloading tv client config
[debug] Loading youtube-sts.91e7c654-main from cache
[youtube] lA1BcL2rVNY: Downloading tv player API JSON
[youtube] lA1BcL2rVNY: Downloading ios player API JSON
[debug] Loading youtube-nsig.91e7c654-main from cache
[debug] [youtube] Decrypted nsig pCe07ra136iy9uB1Hu => issfNABtEioZsw
[debug] [youtube] Decrypted nsig khkWyfPH_rtgAsN-t6 => rC-WDIeY_TKHnQ
[debug] [youtube] lA1BcL2rVNY: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] lA1BcL2rVNY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] lA1BcL2rVNY: Downloading 1 format(s): 612+140
```

But I'm missing the log messages indicating a POT has been generated,  maybe yt-dlp-get-pot plugin generated them. 0.8.5 printed some useful messages:
```
[GetPOT] BgUtilScript: Generating POT via script: /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [GetPOT] BgUtilScript: Executing command to get POT via script: /usr/bin/node /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js -v lA1BcL2rVNY
[debug] [GetPOT] BgUtilScript: stdout:
{"poToken":"MlMlFjfkPolRTCUq5njT4sfidtrAhzJZKElIDu_yg6TRGCPc0mLnTs0Y2MVKZD2o1bMgd8NMN5_lM4VEzRBUhRjMySj0DLLKreaD3XG15iQzRIsTkw==","generatedAt":"2025-06-01T12:53:46.587Z","visitIdentifier":"lA1BcL2rVNY"}
[debug] [youtube+GetPOT] lA1BcL2rVNY: Retrieved a player PO Token for tv client
```

So, how do I know, 1.0 generated POT successfully?

**Comment by Brainicism** [comment]
@pieska 
You can tell that 1.0 generated the POT successfully when you see logs similar to this:
```
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
[debug] [youtube] sE1o6zj0P7g: Retrieved a gvs PO Token for web client
```

1.0 only attempts to fetch a PO token when required (which depends on the client). From your logs, it looks like you're using `TVHTML5`, which doesn't require PO tokens. If you want to test if the plugin is working, try forcing a web client, i.e: `--extractor-arg "youtube:player_client=mweb"`

**Comment by pieska** [comment]
> [@pieska](https://github.com/pieska) You can tell that 1.0 generated the POT successfully when you see logs similar to this:
> 
> ```
> [youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
> [debug] [youtube] sE1o6zj0P7g: Retrieved a gvs PO Token for web client
> ```
> 
> 1.0 only attempts to fetch a PO token when required (which depends on the client). From your logs, it looks like you're using `TVHTML5`, which doesn't require PO tokens. If you want to test if the plugin is working, try forcing a web client, i.e: `--extractor-arg "youtube:player_client=mweb"`

thanks for the explanation, I tried it with 'mweb' but 1.0 did not generate a token:
$ yt-dlp -vvv --extractor-arg "youtube:player_client=mweb" <url>
```
..
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=lA1BcL2rVNY
[youtube] lA1BcL2rVNY: Downloading webpage
[youtube] lA1BcL2rVNY: Downloading mweb client config
[youtube] lA1BcL2rVNY: Downloading mweb player API JSON
[debug] Loading youtube-nsig.91e7c654-main from cache
[debug] [youtube] Decrypted nsig jvcoc6vwR52_Ie6ZOJ => wynA-_qb-hcmRw
[debug] [youtube] Decrypted nsig G7ivS1lwQtkFSBRn6s => 9RnzRPfRhVjstw
WARNING: [youtube] lA1BcL2rVNY: mweb client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=mweb.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
```

**Comment by Brainicism** [comment]
@pieska Can you post the full verbose logs completely unredacted?

**Comment by pieska** [comment]
> [@pieska](https://github.com/pieska) Can you post the full verbose logs completely unredacted?

sure, here it is:
```
$ yt-dlp -v --extractor-arg "youtube:player_client=mweb" https://www.youtube.com/watch?v=lA1BcL2rVNY
[debug] Command-line config: ['-v', '--extractor-arg', 'youtube:player_client=mweb', 'https://www.youtube.com/watch?v=lA1BcL2rVNY']
[debug] User config "/home/user/.config/yt-dlp/config": ['-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '-4', '-cio', '%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.3 (CPython x86_64 64bit) - Linux-6.14.8-300.fc42.x86_64-x86_64-with-glibc2.41 (OpenSSL 3.2.4 11 Feb 2025, glibc 2.41)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.47.2, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=lA1BcL2rVNY
[youtube] lA1BcL2rVNY: Downloading webpage
[youtube] lA1BcL2rVNY: Downloading mweb client config
[youtube] lA1BcL2rVNY: Downloading mweb player API JSON
[debug] Loading youtube-nsig.91e7c654-main from cache
[debug] [youtube] Decrypted nsig wmXxNjo4vcqAgQqNXb => RxvCGpOOLElnaw
[debug] [youtube] Decrypted nsig s0nphRMlJxoOSC7FLw => yfclxw7CHZd1Lw
WARNING: [youtube] lA1BcL2rVNY: mweb client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=mweb.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] lA1BcL2rVNY: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-4g5e6nzl.googlevideo.com/videoplayback?expire=1748822334&ei=3pQ8aK6GINr-i9oPrc232QY&ip=84.189.92.71&id=o-AF_dKPlQXNxMI_kjlmafR_PB4AwzICkFbuI4PY8LfO4q&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1748800734%2C&mh=kz&mm=31%2C26&mn=sn-4g5e6nzl%2Csn-h0jeened&ms=au%2Conr&mv=m&mvi=2&pl=26&rms=au%2Cau&initcwndbps=2248750&bui=AY1jyLMQs8QEac5qnBVU1Ehb2Zx8i__8n4a6OlbGBP9p48xHhtmRr8gf7NY18piQtgiV8eoDIpRd0e6B&spc=l3OVKcx-9pOOr_WMCek1UZ2Xv6gqYM1tfRvVuKiNdEiv73bgNp7wTGnsdkxGNgQpxpowIBwiwCvRfIEMF4fwNSfg&vprv=1&svpuc=1&mime=video%2Fmp4&ns=yX7rmjipS3UqH4Be9VsWDx0Q&rqh=1&gir=yes&clen=33929634&ratebypass=yes&dur=949.649&lmt=1748575479298404&mt=1748800373&fvip=3&fexp=51331020&c=MWEB&sefc=1&txp=3309224&n=RxvCGpOOLElnaw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgSoYw1pQ-rdPB8IJczIl9UORhl0zc7VpWgTdvhvwx0ygCIGHAPR097GdYl7xVRrAY6pH_yh2Q298xUzVtd88lZjnA&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgNqqWlvHS_Gqoi9plqC6lR-BRdQt_7SsCx_z6CLpc9nsCIQD4dI5tHQRrMEGvktl-Qc915tKon-BrjscW8-oAcjF6Kg%3D%3D"
[download] NA/NA-Trump Blows Up Over TACO Nickname, Demands Apology from 60 Minutes & Elon Leaves Washington.mp4 has already been downloaded
[download] 100% of  104.29MiB
[pharaoh@laptop ~]$ cat a
[debug] Command-line config: ['-v', '--extractor-arg', 'youtube:player_client=mweb', 'https://www.youtube.com/watch?v=lA1BcL2rVNY']
[debug] User config "/home/user/.config/yt-dlp/config": ['-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '-4', '-cio', '%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.3 (CPython x86_64 64bit) - Linux-6.14.8-300.fc42.x86_64-x86_64-with-glibc2.41 (OpenSSL 3.2.4 11 Feb 2025, glibc 2.41)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.47.2, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=lA1BcL2rVNY
[youtube] lA1BcL2rVNY: Downloading webpage
[youtube] lA1BcL2rVNY: Downloading mweb client config
[youtube] lA1BcL2rVNY: Downloading mweb player API JSON
[debug] Loading youtube-nsig.91e7c654-main from cache
[debug] [youtube] Decrypted nsig wmXxNjo4vcqAgQqNXb => RxvCGpOOLElnaw
[debug] [youtube] Decrypted nsig s0nphRMlJxoOSC7FLw => yfclxw7CHZd1Lw
WARNING: [youtube] lA1BcL2rVNY: mweb client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=mweb.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] lA1BcL2rVNY: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-4g5e6nzl.googlevideo.com/videoplayback?expire=1748822334&ei=3pQ8aK6GINr-i9oPrc232QY&ip=84.189.92.71&id=o-AF_dKPlQXNxMI_kjlmafR_PB4AwzICkFbuI4PY8LfO4q&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1748800734%2C&mh=kz&mm=31%2C26&mn=sn-4g5e6nzl%2Csn-h0jeened&ms=au%2Conr&mv=m&mvi=2&pl=26&rms=au%2Cau&initcwndbps=2248750&bui=AY1jyLMQs8QEac5qnBVU1Ehb2Zx8i__8n4a6OlbGBP9p48xHhtmRr8gf7NY18piQtgiV8eoDIpRd0e6B&spc=l3OVKcx-9pOOr_WMCek1UZ2Xv6gqYM1tfRvVuKiNdEiv73bgNp7wTGnsdkxGNgQpxpowIBwiwCvRfIEMF4fwNSfg&vprv=1&svpuc=1&mime=video%2Fmp4&ns=yX7rmjipS3UqH4Be9VsWDx0Q&rqh=1&gir=yes&clen=33929634&ratebypass=yes&dur=949.649&lmt=1748575479298404&mt=1748800373&fvip=3&fexp=51331020&c=MWEB&sefc=1&txp=3309224&n=RxvCGpOOLElnaw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgSoYw1pQ-rdPB8IJczIl9UORhl0zc7VpWgTdvhvwx0ygCIGHAPR097GdYl7xVRrAY6pH_yh2Q298xUzVtd88lZjnA&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgNqqWlvHS_Gqoi9plqC6lR-BRdQt_7SsCx_z6CLpc9nsCIQD4dI5tHQRrMEGvktl-Qc915tKon-BrjscW8-oAcjF6Kg%3D%3D"
[download] NA/NA-Trump Blows Up Over TACO Nickname, Demands Apology from 60 Minutes & Elon Leaves Washington.mp4 has already been downloaded
[download] 100% of  104.29MiB
```

**Comment by Brainicism** [comment]
Can you try without `-4`?

**Comment by pieska** [comment]
now with '--ignore-config':
```
$ yt-dlp -v --ignore-config --extractor-arg "youtube:player_client=mweb" https://www.youtube.com/watch?v=lA1BcL2rVNY
[debug] Command-line config: ['-v', '--ignore-config', '--extractor-arg', 'youtube:player_client=mweb', 'https://www.youtube.com/watch?v=lA1BcL2rVNY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.3 (CPython x86_64 64bit) - Linux-6.14.8-300.fc42.x86_64-x86_64-with-glibc2.41 (OpenSSL 3.2.4 11 Feb 2025, glibc 2.41)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.47.2, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/bgutil-ytdlp-pot-provider.zip/yt_dlp_plugins
[debug] Loaded 1859 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=lA1BcL2rVNY
[youtube] lA1BcL2rVNY: Downloading webpage
[youtube] lA1BcL2rVNY: Downloading mweb client config
[debug] [youtube] [pot:bgutil:http] No base_url provided, defaulting to http://127.0.0.1:4416
WARNING: [youtube] [pot:bgutil:http] Error reaching GET http://127.0.0.1:4416/ping (caused by TransportError). Please make sure that the server is reachable at http://127.0.0.1:4416.
[youtube] [pot:bgutil:script] Generating a gvs PO Token for mweb client via bgutil script
[debug] [youtube] [pot:bgutil:script] Executing command to get POT via script: /usr/bin/node /home/user/bgutil-ytdlp-pot-provider/server/build/generate_once.js -c CgtEbWdKRXdRMFA3SSi3yvLBBjIKCgJERRIEEgAgGw%3D%3D
[debug] [youtube] lA1BcL2rVNY: Retrieved a gvs PO Token for mweb client
[youtube] lA1BcL2rVNY: Downloading mweb player API JSON
[debug] Loading youtube-nsig.91e7c654-main from cache
[debug] [youtube] Decrypted nsig _-nu88-HTBjdqtus-W => E---DJAOapiEgA
[debug] [youtube] Decrypted nsig Qt7iVCafEJVG6lHo5U => acW3DBgjrxWtoA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] lA1BcL2rVNY: Downloading 1 format(s): 302+251
[download] Trump Blows Up Over TACO Nickname, Demands Apology from 60 Minutes & Elon Leaves Washington [lA1BcL2rVNY].webm has already been downloaded
```
'-4' makes the difference

**Comment by Brainicism** [comment]
Thanks for checking! This will be fixed in the next release

**Comment by pieska** [comment]
> > Are both your server and your plugin on 1.0.0?
> 
> Yes. This has only started happening on 1.0.0.
> 
> > Could you also provide verbose logs with this modified plugin version? This will help narrow down the issue for us as well
> 
> Sure, it looks like the path's not being parsed.

according to your log you still have the plugin yt-dlp-get-pot installed, try it without it

**Comment by Brainicism** [comment]
> according to your log you still have the plugin yt-dlp-get-pot installed, try it without it

In @brian6932 's case, it looks like it is invoking the new 1.0.0 plugin (that doesn't use ` yt-dlp-get-pot`), but the server's response looks outdated. Highly suspect that it hasn't been transpiled since before 0.8.3

**Comment by brian6932** [comment]
> Can you confirm that you re-transpiled the source code for the server (`npx tsc`)?

I think I did forget to re-run it (it'd be nice if the server printed the version it was running on to stdout on startup). After doing so, the fetch error seems to be gone, but I'm still getting the same parsing error, so I'm pretty sure it wouldn't work without the server running as a daemon.

<details>
<summary>client logs</summary>

```
❯ yt-dlp --rm-cache-dir; yt-dlp -vsF https://www.youtube.com/watch?v=dQw4w9WgXcQ
Removing cache dir ~/.cache\yt-dlp ...
[debug] Command-line config: ['-vsF', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Portable config "~\scoop\apps\yt-dlp-master\current\yt-dlp.conf": ['--extractor-args', 'youtube:formats=dashy;player-client=default,-tv,web_safari,web_embedded;youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2025.05.30.232602 from yt-dlp/yt-dlp-master-builds [3fe72e9ee] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-119779-g6c291232cf-20250531 (setts), ffprobe N-119779-g6c291232cf-20250531
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ~\scoop\apps\yt-dlp-master\current\yt-dlp-plugins\bgutil-ytdlp-pot-provider\yt_dlp_plugins
[debug] Loaded 1860 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot:bgutil:script] Script path doesn't exist: ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.0.0 (external), bgutil:script-1.0.0 (external, unavailable)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[debug] [youtube] [pot:bgutil:http] No base_url provided, defaulting to http://127.0.0.1:4416
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
[debug] [youtube] dQw4w9WgXcQ: Retrieved a gvs PO Token for web client
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web_safari client via bgutil HTTP server
[debug] [youtube] dQw4w9WgXcQ: Retrieved a gvs PO Token for web_safari client
[youtube] dQw4w9WgXcQ: Downloading web safari player API JSON
[youtube] dQw4w9WgXcQ: Downloading web embedded client config
[youtube] dQw4w9WgXcQ: Downloading player 91e7c654-main
[debug] Saving youtube-sts.91e7c654-main to cache
[youtube] dQw4w9WgXcQ: Downloading web embedded player API JSON
[debug] [youtube] dQw4w9WgXcQ: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function 91e7c654-main-109
[debug] Saving youtube-sigfuncs.91e7c654-main-109 to cache
[debug] [youtube] Decrypted nsig yGOKFCuHna4NSRaRw3 => Yk-iz9j7NC-0Bg
[debug] Saving youtube-nsig.91e7c654-main to cache
[debug] [youtube] Decrypted nsig MK09oQr1_b2Y6Q1G7x => yxsM07gvnDx_Rg
[debug] [youtube] Extracting signature function 91e7c654-main-105
[debug] Saving youtube-sigfuncs.91e7c654-main-105 to cache
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for dQw4w9WgXcQ:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2 mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb1 mhtml 160x90       1    │                  mhtml │ images                                  storyboard
sb0 mhtml 320x180      1    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default, low, IOS
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default, high, IOS
249 webm  audio only      2 │    1.18MiB   46k dash  │ audio only          opus        46k 48k low, WEB, webm_dash
250 webm  audio only      2 │    1.55MiB   61k dash  │ audio only          opus        61k 48k low, WEB, webm_dash
140 m4a   audio only      2 │    3.27MiB  130k dash  │ audio only          mp4a.40.2  130k 44k medium, WEB, m4a_dash
251 webm  audio only      2 │    3.28MiB  130k dash  │ audio only          opus       130k 48k medium, WEB, webm_dash
602 mp4   256x144     13    │ ~  2.04MiB   81k m3u8  │ vp09.00.10.08   81k video only          IOS
160 mp4   256x144     25    │    1.78MiB   70k dash  │ avc1.4d400c     70k video only          144p, WEB, mp4_dash
269 mp4   256x144     25    │ ~  3.95MiB  156k m3u8  │ avc1.4D400C    156k video only          IOS
91  mp4   256x144     25    │ ~  3.95MiB  156k m3u8  │ avc1.4D400C         mp4a.40.5           WEB-S
278 webm  256x144     25    │    2.29MiB   91k dash  │ vp9             91k video only          144p, WEB, webm_dash
603 mp4   256x144     25    │ ~  3.88MiB  154k m3u8  │ vp09.00.11.08  154k video only          IOS
394 mp4   256x144     25    │    1.41MiB   56k dash  │ av01.0.00M.08   56k video only          144p, WEB, mp4_dash
133 mp4   426x240     25    │    2.88MiB  114k dash  │ avc1.4d4015    114k video only          240p, WEB, mp4_dash
229 mp4   426x240     25    │ ~  5.73MiB  227k m3u8  │ avc1.4D4015    227k video only          IOS
92  mp4   426x240     25    │ ~  5.73MiB  227k m3u8  │ avc1.4D4015         mp4a.40.5           WEB-S
242 webm  426x240     25    │    3.72MiB  147k dash  │ vp9            147k video only          240p, WEB, webm_dash
604 mp4   426x240     25    │ ~  7.26MiB  287k m3u8  │ vp09.00.20.08  287k video only          IOS
395 mp4   426x240     25    │    2.77MiB  109k dash  │ av01.0.00M.08  109k video only          240p, WEB, mp4_dash
134 mp4   640x360     25    │    5.42MiB  214k dash  │ avc1.4d401e    214k video only          360p, WEB, mp4_dash
230 mp4   640x360     25    │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E    478k video only          IOS
93  mp4   640x360     25    │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E         mp4a.40.2           WEB-S
243 webm  640x360     25    │    6.32MiB  250k dash  │ vp9            250k video only          360p, WEB, webm_dash
605 mp4   640x360     25    │ ~ 14.26MiB  564k m3u8  │ vp09.00.21.08  564k video only          IOS
396 mp4   640x360     25    │    4.85MiB  192k dash  │ av01.0.01M.08  192k video only          360p, WEB, mp4_dash
135 mp4   854x480     25    │    8.28MiB  328k dash  │ avc1.4d401e    328k video only          480p, WEB, mp4_dash
231 mp4   854x480     25    │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E    660k video only          IOS
94  mp4   854x480     25    │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E         mp4a.40.2           WEB-S
244 webm  854x480     25    │    8.92MiB  353k dash  │ vp9            353k video only          480p, WEB, webm_dash
606 mp4   854x480     25    │ ~ 19.74MiB  781k m3u8  │ vp09.00.30.08  781k video only          IOS
397 mp4   854x480     25    │    8.18MiB  324k dash  │ av01.0.04M.08  324k video only          480p, WEB, mp4_dash
136 mp4   1280x720    25    │   16.01MiB  633k dash  │ avc1.4d401f    633k video only          720p, WEB, mp4_dash
232 mp4   1280x720    25    │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F   1131k video only          IOS
95  mp4   1280x720    25    │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F         mp4a.40.2           WEB-S
247 webm  1280x720    25    │   14.65MiB  580k dash  │ vp9            580k video only          720p, WEB, webm_dash
609 mp4   1280x720    25    │ ~ 29.81MiB 1180k m3u8  │ vp09.00.31.08 1180k video only          IOS
398 mp4   1280x720    25    │   14.98MiB  593k dash  │ av01.0.05M.08  593k video only          720p, WEB, mp4_dash
137 mp4   1920x1080   25    │   76.46MiB 3025k dash  │ avc1.640028   3025k video only          1080p, WEB, mp4_dash
270 mp4   1920x1080   25    │ ~123.87MiB 4902k m3u8  │ avc1.640028   4902k video only          IOS
96  mp4   1920x1080   25    │ ~123.87MiB 4902k m3u8  │ avc1.640028         mp4a.40.2           WEB-S
248 webm  1920x1080   25    │   39.24MiB 1552k dash  │ vp9           1552k video only          1080p, WEB, webm_dash
614 mp4   1920x1080   25    │ ~ 71.55MiB 2831k m3u8  │ vp09.00.40.08 2831k video only          IOS
399 mp4   1920x1080   25    │   27.67MiB 1095k dash  │ av01.0.08M.08 1095k video only          1080p, WEB, mp4_dash
616 mp4   1920x1080   25    │ ~144.16MiB 5704k m3u8  │ vp09.00.40.08 5704k video only          Premium, IOS
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dQw4w9WgXcQ: Downloading 1 format(s): 616+251
```
</details>

<details>
<summary>server logs</summary>

```
❯ node $home/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/main.js
Started POT server on port 4416
Generating POT for redacted
poToken: redacted
POT for redacted still fresh, returning cached token
```
</details>

I'm not sure why the server logs state that it's returning a cached token, when I just started the server.

**Comment by Brainicism** [comment]
@brian6932 
Server version logging will be there in the next release (#95). Ideally, the plugin was supposed to throw a warning when the server and plugin versions mismatched too, but the server was reading from `package.json` directly, which mismatched with the actual transpiled code version. Also fixed in the next release (#96).

Right now, variables in the script path (i.e: `%USERPROFILE%`) are not expanded properly but will be fixed in #99. So in the meantime, use an absolute path.

**Comment by Brainicism** [comment]
> I'm not sure why the server logs state that it's returning a cached token, when I just started the server.

We really need clean up the logging, but there's two POT requests happening here:
First request
```
Generating POT for redacted
poToken: redacted
```

Second request:
```
POT for redacted still fresh, returning cached token
```

**Comment by Brainicism** [comment]
Fixed in [v1.1.0](https://github.com/Brainicism/bgutil-ytdlp-pot-provider/releases/tag/1.1.0)

**Comment by brian6932** [comment]
> I'm still getting the same parsing error

I'm still getting this on 1.1.0.

<details>
<summary>client logs</summary>

```
❯ yt-dlp --rm-cache-dir; yt-dlp -vsF https://www.youtube.com/watch?v=dQw4w9WgXcQ
Removing cache dir ~/.cache\yt-dlp ...
[debug] Command-line config: ['-vsF', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Portable config "~\scoop\apps\yt-dlp-master\current\yt-dlp.conf": ['--extractor-args', 'youtube:formats=dashy;player-client=default,-tv,web_safari,web_embedded;youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2025.06.01.232826 from yt-dlp/yt-dlp-master-builds [c723c4e5e] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-119806-g93e53e253a-20250602 (setts), ffprobe N-119806-g93e53e253a-20250602
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ~\scoop\apps\yt-dlp-master\current\yt-dlp-plugins\bgutil-ytdlp-pot-provider\yt_dlp_plugins
[debug] Loaded 1860 extractors
[debug] [youtube] [pot:bgutil:script] No script path passed, defaulting to ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot:bgutil:script] Script path doesn't exist: ~\bgutil-ytdlp-pot-provider\server\build\generate_once.js
[debug] [youtube] [pot] PO Token Providers: bgutil:http-1.1.0 (external), bgutil:script-1.1.0 (external, unavailable)
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[debug] [youtube] [pot:bgutil:http] No base_url provided, defaulting to http://127.0.0.1:4416
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web client via bgutil HTTP server
[debug] [youtube] dQw4w9WgXcQ: Retrieved a gvs PO Token for web client
[youtube] [pot:bgutil:http] Generating a gvs PO Token for web_safari client via bgutil HTTP server
[debug] [youtube] dQw4w9WgXcQ: Retrieved a gvs PO Token for web_safari client
[youtube] dQw4w9WgXcQ: Downloading web safari player API JSON
[youtube] dQw4w9WgXcQ: Downloading web embedded client config
[youtube] dQw4w9WgXcQ: Downloading player 3b4b7883-main
[debug] Saving youtube-sts.3b4b7883-main to cache
[youtube] dQw4w9WgXcQ: Downloading web embedded player API JSON
[debug] [youtube] dQw4w9WgXcQ: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function 3b4b7883-main-105
[debug] Saving youtube-sigfuncs.3b4b7883-main-105 to cache
[debug] [youtube] Decrypted nsig Bdvh9xOF1dOBJR9QZ => vMx0k4lk0-bOwg
[debug] Saving youtube-nsig.3b4b7883-main to cache
WARNING: [youtube] dQw4w9WgXcQ: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] dQw4w9WgXcQ: Some web_safari client https formats have been skipped as they are missing a url. YouTube may have enabled the SABR-only or Server-Side Ad Placement experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for dQw4w9WgXcQ:
ID  EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0 │                  mhtml │ images                         storyboard
sb2 mhtml 80x45        1 │                  mhtml │ images                         storyboard
sb1 mhtml 160x90       1 │                  mhtml │ images                         storyboard
sb0 mhtml 320x180      1 │                  mhtml │ images                         storyboard
233 mp4   audio only     │                  m3u8  │ audio only          unknown    [en] Default, low, IOS
234 mp4   audio only     │                  m3u8  │ audio only          unknown    [en] Default, high, IOS
602 mp4   256x144     13 │ ~  2.04MiB   81k m3u8  │ vp09.00.10.08   81k video only IOS
269 mp4   256x144     25 │ ~  3.95MiB  156k m3u8  │ avc1.4D400C    156k video only IOS
91  mp4   256x144     25 │ ~  3.95MiB  156k m3u8  │ avc1.4D400C         mp4a.40.5  [en] WEB-S
603 mp4   256x144     25 │ ~  3.88MiB  154k m3u8  │ vp09.00.11.08  154k video only IOS
229 mp4   426x240     25 │ ~  5.73MiB  227k m3u8  │ avc1.4D4015    227k video only IOS
92  mp4   426x240     25 │ ~  5.73MiB  227k m3u8  │ avc1.4D4015         mp4a.40.5  [en] WEB-S
604 mp4   426x240     25 │ ~  7.26MiB  287k m3u8  │ vp09.00.20.08  287k video only IOS
230 mp4   640x360     25 │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E    478k video only IOS
93  mp4   640x360     25 │ ~ 12.09MiB  478k m3u8  │ avc1.4D401E         mp4a.40.2  [en] WEB-S
605 mp4   640x360     25 │ ~ 14.26MiB  564k m3u8  │ vp09.00.21.08  564k video only IOS
231 mp4   854x480     25 │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E    660k video only IOS
94  mp4   854x480     25 │ ~ 16.69MiB  660k m3u8  │ avc1.4D401E         mp4a.40.2  [en] WEB-S
606 mp4   854x480     25 │ ~ 19.74MiB  781k m3u8  │ vp09.00.30.08  781k video only IOS
232 mp4   1280x720    25 │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F   1131k video only IOS
95  mp4   1280x720    25 │ ~ 28.59MiB 1131k m3u8  │ avc1.4D401F         mp4a.40.2  [en] WEB-S
609 mp4   1280x720    25 │ ~ 29.81MiB 1180k m3u8  │ vp09.00.31.08 1180k video only IOS
270 mp4   1920x1080   25 │ ~123.87MiB 4902k m3u8  │ avc1.640028   4902k video only IOS
96  mp4   1920x1080   25 │ ~123.87MiB 4902k m3u8  │ avc1.640028         mp4a.40.2  [en] WEB-S
614 mp4   1920x1080   25 │ ~ 71.55MiB 2831k m3u8  │ vp09.00.40.08 2831k video only IOS
616 mp4   1920x1080   25 │ ~144.16MiB 5704k m3u8  │ vp09.00.40.08 5704k video only Premium, IOS
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dQw4w9WgXcQ: Downloading 1 format(s): 616+234
```
</details>

<details>
<summary>server logs</summary>

```
❯ node $home/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/main.js
Started POT server (v1.1.0) on port 4416
Generating POT for redacted
poToken: redacted
POT for redacted still fresh, returning cached token
```
</details>

**Comment by grqz** [comment]
you need to use separate --extractor-args for youtube and youtubepot-bgutilscript, so
```
--extractor-args
youtube:...:...,...;...:....
--extractor-args
youtubepot-bgutilscript:script_path=%USERPROFILE%/src/github.com/Brainicism/bgutil-ytdlp-pot-provider/server/build/generate_once.js
```

**Comment by brian6932** [comment]
Yea, that works.
